name: garagesale
description: "Hyper garage sale."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_storage: ^11.5.5
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  modal_progress_hud_nsn: ^0.4.0
  image_picker: ^1.0.4
  camera: ^0.10.5+6
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/applogo.jpg
