name: hero_animation
publish_to: none
description: Shows how to create a simple Hero transition.

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/flippers-alpha.png
    - images/beachball-alpha.png
    - images/binoculars-alpha.png
    - images/chair-alpha.png
