// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7wJ_vEJjK6Y_oq8RQgfwHK5oPUo0WrA',
    appId: '1:436179807286:web:e3972047822cafeea1bc97',
    messagingSenderId: '436179807286',
    projectId: 'finalproject-797f9',
    authDomain: 'finalproject-797f9.firebaseapp.com',
    storageBucket: 'finalproject-797f9.appspot.com',
    measurementId: 'G-N4DWFMJDD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPc5lP65sOlc-WM3b0_7ji4OqRGOHw3Q',
    appId: '1:436179807286:android:967294d39de1bdc0a1bc97',
    messagingSenderId: '436179807286',
    projectId: 'finalproject-797f9',
    storageBucket: 'finalproject-797f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYupWPInn4YEh_A9pIqI8qZZQrGGcPMsk',
    appId: '1:436179807286:ios:7b5913fb0b48a9f0a1bc97',
    messagingSenderId: '436179807286',
    projectId: 'finalproject-797f9',
    storageBucket: 'finalproject-797f9.appspot.com',
    iosBundleId: 'com.example.garagesale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYupWPInn4YEh_A9pIqI8qZZQrGGcPMsk',
    appId: '1:436179807286:ios:f072365c927a6765a1bc97',
    messagingSenderId: '436179807286',
    projectId: 'finalproject-797f9',
    storageBucket: 'finalproject-797f9.appspot.com',
    iosBundleId: 'com.example.garagesale.RunnerTests',
  );
}
